#!/usr/bin/env sh

GIT_COMMIT="$(git rev-parse HEAD)"
# XMTP_GO_CLIENT_VERSION="$(go list -json -m all | jq -r '. | select(.Path == "github.com/xmtp/proto") | .Version')"

docker build \
    -t "${IMAGE_TAG}" \
    --build-arg="GIT_COMMIT=${GIT_COMMIT}" \
    --build-arg="XMTP_GO_CLIENT_VERSION=${XMTP_GO_CLIENT_VERSION}" \
    .
