#!/usr/bin/env bash

set -e

if [ -n "$(go env GOBIN)" ]; then
    FOUND_GOBIN=$(go env GOBIN)
    export PATH="${FOUND_GOBIN}:${PATH}"
fi

if [ -n "$(go env GOPATH)" ]; then 
    FOUND_GOPATH=$(go env GOPATH)
    export PATH="${FOUND_GOPATH}/bin:${PATH}"
fi

if ! command -v buf &>/dev/null; then
    go install go install github.com/bufbuild/buf/cmd/buf@latest
fi

if ! command -v protoc-gen-go &>/dev/null; then
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
fi

if ! command -v protoc-gen-connect-go &>/dev/null; then
    go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
fi

rm -rf ./pkg/proto
buf build
buf generate