// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installations.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const getLatestInstallations = `-- name: GetLatestInstallations :many
SELECT ddm.id, ddm.installation_id, ddm.kind, ddm.token, ddm.created_at, ddm.updated_at
FROM installations i
JOIN LATERAL (
    SELECT d.id, d.installation_id, d.kind, d.token, d.created_at, d.updated_at
    FROM device_delivery_mechanisms d
    WHERE d.installation_id = i.id
    ORDER BY d.updated_at DESC, d.id DESC
    LIMIT 1
) ddm ON TRUE
WHERE i.id = ANY($1::text[])
  AND i.deleted_at IS NULL
ORDER BY i.id DESC
`

type GetLatestInstallationsRow struct {
	ID             int64
	InstallationID string
	Kind           string
	Token          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetLatestInstallations(ctx context.Context, installationIds []string) ([]GetLatestInstallationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestInstallations, pq.Array(installationIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestInstallationsRow
	for rows.Next() {
		var i GetLatestInstallationsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.Kind,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInstallation = `-- name: SoftDeleteInstallation :exec
UPDATE installations
SET deleted_at = $1
WHERE id = $2
`

type SoftDeleteInstallationParams struct {
	DeletedAt sql.NullTime
	ID        string
}

func (q *Queries) SoftDeleteInstallation(ctx context.Context, arg SoftDeleteInstallationParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteInstallation, arg.DeletedAt, arg.ID)
	return err
}

const upsertDeviceDeliveryMechanism = `-- name: UpsertDeviceDeliveryMechanism :exec
INSERT INTO device_delivery_mechanisms (
    installation_id,
    kind,
    token,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    COALESCE($4, clock_timestamp())
)
ON CONFLICT (installation_id, kind, token) DO UPDATE
SET updated_at = EXCLUDED.updated_at
`

type UpsertDeviceDeliveryMechanismParams struct {
	InstallationID string
	Kind           string
	Token          string
	UpdatedAt      interface{}
}

func (q *Queries) UpsertDeviceDeliveryMechanism(ctx context.Context, arg UpsertDeviceDeliveryMechanismParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeviceDeliveryMechanism,
		arg.InstallationID,
		arg.Kind,
		arg.Token,
		arg.UpdatedAt,
	)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :exec
INSERT INTO installations (id)
VALUES ($1)
ON CONFLICT (id) DO UPDATE
SET deleted_at = NULL
`

func (q *Queries) UpsertInstallation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, upsertInstallation, id)
	return err
}
