// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type DeviceDeliveryMechanism struct {
	ID             int32
	InstallationID string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Kind           string
	Token          string
}

type Installation struct {
	ID        string
	CreatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Subscription struct {
	ID             int32
	InstallationID string
	CreatedAt      sql.NullTime
	Topic          []byte
	IsActive       sql.NullBool
	IsSilent       sql.NullBool
}

type SubscriptionHmacKey struct {
	SubscriptionID             int32
	ThirtyDayPeriodsSinceEpoch int32
	CreatedAt                  sql.NullTime
	UpdatedAt                  sql.NullTime
	Key                        []byte
}
