// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type DeviceDeliveryMechanism struct {
	ID             int64
	InstallationID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Kind           string
	Token          string
}

type Installation struct {
	ID            string
	CreatedAt     time.Time
	DeletedAt     sql.NullTime
	PayloadFormat int16
}

type Subscription struct {
	ID             int64
	InstallationID string
	CreatedAt      time.Time
	IsActive       bool
	IsSilent       bool
	Topic          []byte
}

type SubscriptionHmacKey struct {
	SubscriptionID             int64
	ThirtyDayPeriodsSinceEpoch int32
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	Key                        []byte
}
