// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const deactivateSubscriptions = `-- name: DeactivateSubscriptions :exec
UPDATE subscriptions
SET is_active = FALSE
WHERE installation_id = $1
  AND topic = ANY($2::bytea[])
`

type DeactivateSubscriptionsParams struct {
	InstallationID string
	Topics         [][]byte
}

func (q *Queries) DeactivateSubscriptions(ctx context.Context, arg DeactivateSubscriptionsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateSubscriptions, arg.InstallationID, pq.Array(arg.Topics))
	return err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (
    installation_id,
    topic,
    is_active,
    is_silent
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertSubscriptionParams struct {
	InstallationID string
	Topic          []byte
	IsActive       sql.NullBool
	IsSilent       sql.NullBool
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, insertSubscription,
		arg.InstallationID,
		arg.Topic,
		arg.IsActive,
		arg.IsSilent,
	)
	return err
}

const listActiveSubscriptionsByTopicAndPeriod = `-- name: ListActiveSubscriptionsByTopicAndPeriod :many
SELECT
    s.id,
    s.created_at,
    s.installation_id,
    s.topic,
    s.is_active,
    s.is_silent,
    shk.subscription_id IS NOT NULL AS has_hmac_key,
    shk.thirty_day_periods_since_epoch,
    shk.key
FROM subscriptions AS s
LEFT JOIN subscription_hmac_keys AS shk
    ON shk.subscription_id = s.id
   AND shk.thirty_day_periods_since_epoch = $1
WHERE s.topic = $2
  AND s.is_active = TRUE
ORDER BY s.id
`

type ListActiveSubscriptionsByTopicAndPeriodParams struct {
	ThirtyDayPeriod int32
	Topic           []byte
}

type ListActiveSubscriptionsByTopicAndPeriodRow struct {
	ID                         int32
	CreatedAt                  sql.NullTime
	InstallationID             string
	Topic                      []byte
	IsActive                   sql.NullBool
	IsSilent                   sql.NullBool
	HasHmacKey                 interface{}
	ThirtyDayPeriodsSinceEpoch sql.NullInt32
	Key                        []byte
}

func (q *Queries) ListActiveSubscriptionsByTopicAndPeriod(ctx context.Context, arg ListActiveSubscriptionsByTopicAndPeriodParams) ([]ListActiveSubscriptionsByTopicAndPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptionsByTopicAndPeriod, arg.ThirtyDayPeriod, arg.Topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSubscriptionsByTopicAndPeriodRow
	for rows.Next() {
		var i ListActiveSubscriptionsByTopicAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.InstallationID,
			&i.Topic,
			&i.IsActive,
			&i.IsSilent,
			&i.HasHmacKey,
			&i.ThirtyDayPeriodsSinceEpoch,
			&i.Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateSubscriptions = `-- name: ReactivateSubscriptions :many
UPDATE subscriptions
SET is_active = TRUE
WHERE installation_id = $1
  AND topic = ANY($2::bytea[])
RETURNING id, created_at, installation_id, topic, is_active, is_silent
`

type ReactivateSubscriptionsParams struct {
	InstallationID string
	Topics         [][]byte
}

type ReactivateSubscriptionsRow struct {
	ID             int32
	CreatedAt      sql.NullTime
	InstallationID string
	Topic          []byte
	IsActive       sql.NullBool
	IsSilent       sql.NullBool
}

func (q *Queries) ReactivateSubscriptions(ctx context.Context, arg ReactivateSubscriptionsParams) ([]ReactivateSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, reactivateSubscriptions, arg.InstallationID, pq.Array(arg.Topics))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReactivateSubscriptionsRow
	for rows.Next() {
		var i ReactivateSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.InstallationID,
			&i.Topic,
			&i.IsActive,
			&i.IsSilent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    installation_id,
    topic,
    is_active,
    is_silent
)
VALUES (
    $1,
    $2,
    TRUE,
    $3
)
ON CONFLICT (installation_id, topic) DO UPDATE
SET is_active = TRUE,
    is_silent = EXCLUDED.is_silent
RETURNING id, created_at, installation_id, topic, is_active, is_silent
`

type UpsertSubscriptionParams struct {
	InstallationID string
	Topic          []byte
	IsSilent       sql.NullBool
}

type UpsertSubscriptionRow struct {
	ID             int32
	CreatedAt      sql.NullTime
	InstallationID string
	Topic          []byte
	IsActive       sql.NullBool
	IsSilent       sql.NullBool
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (UpsertSubscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, upsertSubscription, arg.InstallationID, arg.Topic, arg.IsSilent)
	var i UpsertSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.InstallationID,
		&i.Topic,
		&i.IsActive,
		&i.IsSilent,
	)
	return i, err
}

const upsertSubscriptionHmacKey = `-- name: UpsertSubscriptionHmacKey :exec
INSERT INTO subscription_hmac_keys (
    subscription_id,
    thirty_day_periods_since_epoch,
    key
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (subscription_id, thirty_day_periods_since_epoch) DO UPDATE
SET key = EXCLUDED.key,
    updated_at = NOW()
`

type UpsertSubscriptionHmacKeyParams struct {
	SubscriptionID             int32
	ThirtyDayPeriodsSinceEpoch int32
	Key                        []byte
}

func (q *Queries) UpsertSubscriptionHmacKey(ctx context.Context, arg UpsertSubscriptionHmacKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscriptionHmacKey, arg.SubscriptionID, arg.ThirtyDayPeriodsSinceEpoch, arg.Key)
	return err
}
