// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const batchInsertSubscriptions = `-- name: BatchInsertSubscriptions :exec
INSERT INTO subscriptions (installation_id, topic, is_active, is_silent)
SELECT $1::text, t.topic, TRUE, FALSE
FROM unnest($2::bytea[]) AS t(topic)
ON CONFLICT (installation_id, topic) DO NOTHING
`

type BatchInsertSubscriptionsParams struct {
	InstallationID string
	Topics         [][]byte
}

func (q *Queries) BatchInsertSubscriptions(ctx context.Context, arg BatchInsertSubscriptionsParams) error {
	_, err := q.db.ExecContext(ctx, batchInsertSubscriptions, arg.InstallationID, pq.Array(arg.Topics))
	return err
}

const batchUpsertSubscriptionHmacKeys = `-- name: BatchUpsertSubscriptionHmacKeys :exec
INSERT INTO subscription_hmac_keys (subscription_id, thirty_day_periods_since_epoch, key)
SELECT t.sub_id, t.period, t.hmac_key
FROM ROWS FROM (
    unnest($1::bigint[]),
    unnest($2::integer[]),
    unnest($3::bytea[])
) AS t(sub_id, period, hmac_key)
ON CONFLICT (subscription_id, thirty_day_periods_since_epoch) DO UPDATE
SET key = EXCLUDED.key, updated_at = NOW()
`

type BatchUpsertSubscriptionHmacKeysParams struct {
	SubscriptionIds []int64
	Periods         []int32
	Keys            [][]byte
}

func (q *Queries) BatchUpsertSubscriptionHmacKeys(ctx context.Context, arg BatchUpsertSubscriptionHmacKeysParams) error {
	_, err := q.db.ExecContext(ctx, batchUpsertSubscriptionHmacKeys, pq.Array(arg.SubscriptionIds), pq.Array(arg.Periods), pq.Array(arg.Keys))
	return err
}

const batchUpsertSubscriptions = `-- name: BatchUpsertSubscriptions :many
INSERT INTO subscriptions (installation_id, topic, is_active, is_silent)
SELECT $1::text, t.topic, TRUE, t.is_silent
FROM ROWS FROM (
    unnest($2::bytea[]),
    unnest($3::boolean[])
) AS t(topic, is_silent)
ON CONFLICT (installation_id, topic) DO UPDATE
SET is_active = TRUE, is_silent = EXCLUDED.is_silent
RETURNING id, topic
`

type BatchUpsertSubscriptionsParams struct {
	InstallationID string
	Topics         [][]byte
	IsSilents      []bool
}

type BatchUpsertSubscriptionsRow struct {
	ID    int64
	Topic []byte
}

func (q *Queries) BatchUpsertSubscriptions(ctx context.Context, arg BatchUpsertSubscriptionsParams) ([]BatchUpsertSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, batchUpsertSubscriptions, arg.InstallationID, pq.Array(arg.Topics), pq.Array(arg.IsSilents))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchUpsertSubscriptionsRow
	for rows.Next() {
		var i BatchUpsertSubscriptionsRow
		if err := rows.Scan(&i.ID, &i.Topic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deactivateInstallationSubscriptions = `-- name: DeactivateInstallationSubscriptions :exec
UPDATE subscriptions
SET is_active = FALSE
WHERE installation_id = $1
  AND is_active = TRUE
`

func (q *Queries) DeactivateInstallationSubscriptions(ctx context.Context, installationID string) error {
	_, err := q.db.ExecContext(ctx, deactivateInstallationSubscriptions, installationID)
	return err
}

const deactivateSubscriptions = `-- name: DeactivateSubscriptions :exec
UPDATE subscriptions
SET is_active = FALSE
WHERE installation_id = $1
  AND topic = ANY($2::bytea[])
`

type DeactivateSubscriptionsParams struct {
	InstallationID string
	Topics         [][]byte
}

func (q *Queries) DeactivateSubscriptions(ctx context.Context, arg DeactivateSubscriptionsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateSubscriptions, arg.InstallationID, pq.Array(arg.Topics))
	return err
}

const listActiveSubscriptionsByTopicAndPeriod = `-- name: ListActiveSubscriptionsByTopicAndPeriod :many
SELECT
    s.id,
    s.created_at,
    s.installation_id,
    s.topic,
    s.is_active,
    s.is_silent,
    shk.subscription_id IS NOT NULL AS has_hmac_key,
    shk.thirty_day_periods_since_epoch,
    shk.key
FROM subscriptions AS s
LEFT JOIN subscription_hmac_keys AS shk
    ON shk.subscription_id = s.id
   AND shk.thirty_day_periods_since_epoch = $1
WHERE s.topic = $2
  AND s.is_active = TRUE
ORDER BY s.id
`

type ListActiveSubscriptionsByTopicAndPeriodParams struct {
	ThirtyDayPeriod int32
	Topic           []byte
}

type ListActiveSubscriptionsByTopicAndPeriodRow struct {
	ID                         int64
	CreatedAt                  time.Time
	InstallationID             string
	Topic                      []byte
	IsActive                   bool
	IsSilent                   bool
	HasHmacKey                 interface{}
	ThirtyDayPeriodsSinceEpoch sql.NullInt32
	Key                        []byte
}

func (q *Queries) ListActiveSubscriptionsByTopicAndPeriod(ctx context.Context, arg ListActiveSubscriptionsByTopicAndPeriodParams) ([]ListActiveSubscriptionsByTopicAndPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptionsByTopicAndPeriod, arg.ThirtyDayPeriod, arg.Topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSubscriptionsByTopicAndPeriodRow
	for rows.Next() {
		var i ListActiveSubscriptionsByTopicAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.InstallationID,
			&i.Topic,
			&i.IsActive,
			&i.IsSilent,
			&i.HasHmacKey,
			&i.ThirtyDayPeriodsSinceEpoch,
			&i.Key,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateSubscriptions = `-- name: ReactivateSubscriptions :many
UPDATE subscriptions
SET is_active = TRUE
WHERE installation_id = $1
  AND topic = ANY($2::bytea[])
RETURNING id, created_at, installation_id, topic, is_active, is_silent
`

type ReactivateSubscriptionsParams struct {
	InstallationID string
	Topics         [][]byte
}

type ReactivateSubscriptionsRow struct {
	ID             int64
	CreatedAt      time.Time
	InstallationID string
	Topic          []byte
	IsActive       bool
	IsSilent       bool
}

func (q *Queries) ReactivateSubscriptions(ctx context.Context, arg ReactivateSubscriptionsParams) ([]ReactivateSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, reactivateSubscriptions, arg.InstallationID, pq.Array(arg.Topics))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReactivateSubscriptionsRow
	for rows.Next() {
		var i ReactivateSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.InstallationID,
			&i.Topic,
			&i.IsActive,
			&i.IsSilent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
