#!/usr/bin/env bash
set -e

(
  cd dev/kotlin/protoc
  docker build --platform linux/x86_64 -t xmtp/protoc-kotlin . 
)

rm -rf ./kotlin/lib/src/main/kotlin
mkdir -p ./kotlin/lib/src/main/kotlin

# Need Plugins for both Java and Kotlin see: https://developers.google.com/protocol-buffers/docs/reference/kotlin-generated
docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
    -I=./proto \
    --proto_path=./proto \
    --plugin=protoc-gen-grpckt=dev/kotlin/protoc/protoc-gen-grpc-kotlin.sh \
    --plugin=protoc-gen-java_rpc=../../build/binaries/java_pluginExecutable/protoc-gen-grpc-java \
    --grpc-java_out=lite:./kotlin/lib/src/main/kotlin \
    --java_out=lite:./kotlin/lib/src/main/kotlin \
  proto/notifications/v1/service.proto

docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
  -I=./proto \
  --proto_path=./proto \
  --experimental_allow_proto3_optional \
  --java_out=lite:./kotlin/lib/src/main/kotlin \
  proto/notifications/v1/service.proto