// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	interfaces "github.com/xmtp/example-notification-server-go/pkg/interfaces"
)

// Subscriptions is an autogenerated mock type for the Subscriptions type
type Subscriptions struct {
	mock.Mock
}

// GetSubscriptions provides a mock function with given fields: ctx, topic
func (_m *Subscriptions) GetSubscriptions(ctx context.Context, topic string) ([]interfaces.Subscription, error) {
	ret := _m.Called(ctx, topic)

	var r0 []interfaces.Subscription
	if rf, ok := ret.Get(0).(func(context.Context, string) []interfaces.Subscription); ok {
		r0 = rf(ctx, topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, topic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: ctx, installationId, topics
func (_m *Subscriptions) Subscribe(ctx context.Context, installationId string, topics []string) error {
	ret := _m.Called(ctx, installationId, topics)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, installationId, topics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: ctx, installationId, topics
func (_m *Subscriptions) Unsubscribe(ctx context.Context, installationId string, topics []string) error {
	ret := _m.Called(ctx, installationId, topics)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, installationId, topics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSubscriptions interface {
	mock.TestingT
	Cleanup(func())
}

// NewSubscriptions creates a new instance of Subscriptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubscriptions(t mockConstructorTestingTNewSubscriptions) *Subscriptions {
	mock := &Subscriptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
