// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: notifications/v1/service.proto

package notificationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An union of possible delibery mechanisms
type DeliveryMechanism struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to DeliveryMechanismType:
	//
	//	*DeliveryMechanism_ApnsDeviceToken
	//	*DeliveryMechanism_FirebaseDeviceToken
	//	*DeliveryMechanism_CustomToken
	DeliveryMechanismType isDeliveryMechanism_DeliveryMechanismType `protobuf_oneof:"delivery_mechanism_type"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeliveryMechanism) Reset() {
	*x = DeliveryMechanism{}
	mi := &file_notifications_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryMechanism) ProtoMessage() {}

func (x *DeliveryMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryMechanism.ProtoReflect.Descriptor instead.
func (*DeliveryMechanism) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryMechanism) GetDeliveryMechanismType() isDeliveryMechanism_DeliveryMechanismType {
	if x != nil {
		return x.DeliveryMechanismType
	}
	return nil
}

func (x *DeliveryMechanism) GetApnsDeviceToken() string {
	if x != nil {
		if x, ok := x.DeliveryMechanismType.(*DeliveryMechanism_ApnsDeviceToken); ok {
			return x.ApnsDeviceToken
		}
	}
	return ""
}

func (x *DeliveryMechanism) GetFirebaseDeviceToken() string {
	if x != nil {
		if x, ok := x.DeliveryMechanismType.(*DeliveryMechanism_FirebaseDeviceToken); ok {
			return x.FirebaseDeviceToken
		}
	}
	return ""
}

func (x *DeliveryMechanism) GetCustomToken() string {
	if x != nil {
		if x, ok := x.DeliveryMechanismType.(*DeliveryMechanism_CustomToken); ok {
			return x.CustomToken
		}
	}
	return ""
}

type isDeliveryMechanism_DeliveryMechanismType interface {
	isDeliveryMechanism_DeliveryMechanismType()
}

type DeliveryMechanism_ApnsDeviceToken struct {
	ApnsDeviceToken string `protobuf:"bytes,1,opt,name=apns_device_token,json=apnsDeviceToken,proto3,oneof"`
}

type DeliveryMechanism_FirebaseDeviceToken struct {
	FirebaseDeviceToken string `protobuf:"bytes,2,opt,name=firebase_device_token,json=firebaseDeviceToken,proto3,oneof"`
}

type DeliveryMechanism_CustomToken struct {
	CustomToken string `protobuf:"bytes,3,opt,name=custom_token,json=customToken,proto3,oneof"`
}

func (*DeliveryMechanism_ApnsDeviceToken) isDeliveryMechanism_DeliveryMechanismType() {}

func (*DeliveryMechanism_FirebaseDeviceToken) isDeliveryMechanism_DeliveryMechanismType() {}

func (*DeliveryMechanism_CustomToken) isDeliveryMechanism_DeliveryMechanismType() {}

// A request to register an installation with the service
type RegisterInstallationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstallationId    string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	DeliveryMechanism *DeliveryMechanism     `protobuf:"bytes,2,opt,name=delivery_mechanism,json=deliveryMechanism,proto3" json:"delivery_mechanism,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterInstallationRequest) Reset() {
	*x = RegisterInstallationRequest{}
	mi := &file_notifications_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstallationRequest) ProtoMessage() {}

func (x *RegisterInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstallationRequest.ProtoReflect.Descriptor instead.
func (*RegisterInstallationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterInstallationRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *RegisterInstallationRequest) GetDeliveryMechanism() *DeliveryMechanism {
	if x != nil {
		return x.DeliveryMechanism
	}
	return nil
}

// Response to RegisterInstallationRequest
type RegisterInstallationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	ValidUntil     uint64                 `protobuf:"varint,2,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterInstallationResponse) Reset() {
	*x = RegisterInstallationResponse{}
	mi := &file_notifications_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstallationResponse) ProtoMessage() {}

func (x *RegisterInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstallationResponse.ProtoReflect.Descriptor instead.
func (*RegisterInstallationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterInstallationResponse) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *RegisterInstallationResponse) GetValidUntil() uint64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

// Delete an installation from the service
type DeleteInstallationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteInstallationRequest) Reset() {
	*x = DeleteInstallationRequest{}
	mi := &file_notifications_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstallationRequest) ProtoMessage() {}

func (x *DeleteInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstallationRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstallationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteInstallationRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

// A subscription with associated metadata
type Subscription struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Topic         string                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	HmacKeys      []*Subscription_HmacKey `protobuf:"bytes,2,rep,name=hmac_keys,json=hmacKeys,proto3" json:"hmac_keys,omitempty"`
	IsSilent      bool                    `protobuf:"varint,3,opt,name=is_silent,json=isSilent,proto3" json:"is_silent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_notifications_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *Subscription) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Subscription) GetHmacKeys() []*Subscription_HmacKey {
	if x != nil {
		return x.HmacKeys
	}
	return nil
}

func (x *Subscription) GetIsSilent() bool {
	if x != nil {
		return x.IsSilent
	}
	return false
}

// A request to subscribe to a list of topics and update the associated metadata
type SubscribeWithMetadataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	Subscriptions  []*Subscription        `protobuf:"bytes,2,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeWithMetadataRequest) Reset() {
	*x = SubscribeWithMetadataRequest{}
	mi := &file_notifications_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeWithMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeWithMetadataRequest) ProtoMessage() {}

func (x *SubscribeWithMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeWithMetadataRequest.ProtoReflect.Descriptor instead.
func (*SubscribeWithMetadataRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeWithMetadataRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *SubscribeWithMetadataRequest) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// Subscribe to a list of topics
type SubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	Topics         []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_notifications_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// Unsubscribe from a list of topics
type UnsubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	Topics         []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_notifications_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *UnsubscribeRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *UnsubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Subscription_HmacKey struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ThirtyDayPeriodsSinceEpoch uint32                 `protobuf:"varint,1,opt,name=thirty_day_periods_since_epoch,json=thirtyDayPeriodsSinceEpoch,proto3" json:"thirty_day_periods_since_epoch,omitempty"`
	Key                        []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Subscription_HmacKey) Reset() {
	*x = Subscription_HmacKey{}
	mi := &file_notifications_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription_HmacKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription_HmacKey) ProtoMessage() {}

func (x *Subscription_HmacKey) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription_HmacKey.ProtoReflect.Descriptor instead.
func (*Subscription_HmacKey) Descriptor() ([]byte, []int) {
	return file_notifications_v1_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Subscription_HmacKey) GetThirtyDayPeriodsSinceEpoch() uint32 {
	if x != nil {
		return x.ThirtyDayPeriodsSinceEpoch
	}
	return 0
}

func (x *Subscription_HmacKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_notifications_v1_service_proto protoreflect.FileDescriptor

const file_notifications_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1enotifications/v1/service.proto\x12\x10notifications.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xb7\x01\n" +
	"\x11DeliveryMechanism\x12,\n" +
	"\x11apns_device_token\x18\x01 \x01(\tH\x00R\x0fapnsDeviceToken\x124\n" +
	"\x15firebase_device_token\x18\x02 \x01(\tH\x00R\x13firebaseDeviceToken\x12#\n" +
	"\fcustom_token\x18\x03 \x01(\tH\x00R\vcustomTokenB\x19\n" +
	"\x17delivery_mechanism_type\"\x9a\x01\n" +
	"\x1bRegisterInstallationRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12R\n" +
	"\x12delivery_mechanism\x18\x02 \x01(\v2#.notifications.v1.DeliveryMechanismR\x11deliveryMechanism\"h\n" +
	"\x1cRegisterInstallationResponse\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12\x1f\n" +
	"\vvalid_until\x18\x02 \x01(\x04R\n" +
	"validUntil\"D\n" +
	"\x19DeleteInstallationRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\"\xe7\x01\n" +
	"\fSubscription\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12C\n" +
	"\thmac_keys\x18\x02 \x03(\v2&.notifications.v1.Subscription.HmacKeyR\bhmacKeys\x12\x1b\n" +
	"\tis_silent\x18\x03 \x01(\bR\bisSilent\x1a_\n" +
	"\aHmacKey\x12B\n" +
	"\x1ethirty_day_periods_since_epoch\x18\x01 \x01(\rR\x1athirtyDayPeriodsSinceEpoch\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\x8d\x01\n" +
	"\x1cSubscribeWithMetadataRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12D\n" +
	"\rsubscriptions\x18\x02 \x03(\v2\x1e.notifications.v1.SubscriptionR\rsubscriptions\"S\n" +
	"\x10SubscribeRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"U\n" +
	"\x12UnsubscribeRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\tR\x0einstallationId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics2\xd8\x03\n" +
	"\rNotifications\x12u\n" +
	"\x14RegisterInstallation\x12-.notifications.v1.RegisterInstallationRequest\x1a..notifications.v1.RegisterInstallationResponse\x12Y\n" +
	"\x12DeleteInstallation\x12+.notifications.v1.DeleteInstallationRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\tSubscribe\x12\".notifications.v1.SubscribeRequest\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\x15SubscribeWithMetadata\x12..notifications.v1.SubscribeWithMetadataRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\vUnsubscribe\x12$.notifications.v1.UnsubscribeRequest\x1a\x16.google.protobuf.EmptyB\xe0\x01\n" +
	"\x14com.notifications.v1B\fServiceProtoP\x01ZYgithub.com/xmtp/example-notification-server-go/pkg/proto/notifications/v1;notificationsv1\xa2\x02\x03NXX\xaa\x02\x10Notifications.V1\xca\x02\x10Notifications\\V1\xe2\x02\x1cNotifications\\V1\\GPBMetadata\xea\x02\x11Notifications::V1b\x06proto3"

var (
	file_notifications_v1_service_proto_rawDescOnce sync.Once
	file_notifications_v1_service_proto_rawDescData []byte
)

func file_notifications_v1_service_proto_rawDescGZIP() []byte {
	file_notifications_v1_service_proto_rawDescOnce.Do(func() {
		file_notifications_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_v1_service_proto_rawDesc), len(file_notifications_v1_service_proto_rawDesc)))
	})
	return file_notifications_v1_service_proto_rawDescData
}

var file_notifications_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_notifications_v1_service_proto_goTypes = []any{
	(*DeliveryMechanism)(nil),            // 0: notifications.v1.DeliveryMechanism
	(*RegisterInstallationRequest)(nil),  // 1: notifications.v1.RegisterInstallationRequest
	(*RegisterInstallationResponse)(nil), // 2: notifications.v1.RegisterInstallationResponse
	(*DeleteInstallationRequest)(nil),    // 3: notifications.v1.DeleteInstallationRequest
	(*Subscription)(nil),                 // 4: notifications.v1.Subscription
	(*SubscribeWithMetadataRequest)(nil), // 5: notifications.v1.SubscribeWithMetadataRequest
	(*SubscribeRequest)(nil),             // 6: notifications.v1.SubscribeRequest
	(*UnsubscribeRequest)(nil),           // 7: notifications.v1.UnsubscribeRequest
	(*Subscription_HmacKey)(nil),         // 8: notifications.v1.Subscription.HmacKey
	(*emptypb.Empty)(nil),                // 9: google.protobuf.Empty
}
var file_notifications_v1_service_proto_depIdxs = []int32{
	0, // 0: notifications.v1.RegisterInstallationRequest.delivery_mechanism:type_name -> notifications.v1.DeliveryMechanism
	8, // 1: notifications.v1.Subscription.hmac_keys:type_name -> notifications.v1.Subscription.HmacKey
	4, // 2: notifications.v1.SubscribeWithMetadataRequest.subscriptions:type_name -> notifications.v1.Subscription
	1, // 3: notifications.v1.Notifications.RegisterInstallation:input_type -> notifications.v1.RegisterInstallationRequest
	3, // 4: notifications.v1.Notifications.DeleteInstallation:input_type -> notifications.v1.DeleteInstallationRequest
	6, // 5: notifications.v1.Notifications.Subscribe:input_type -> notifications.v1.SubscribeRequest
	5, // 6: notifications.v1.Notifications.SubscribeWithMetadata:input_type -> notifications.v1.SubscribeWithMetadataRequest
	7, // 7: notifications.v1.Notifications.Unsubscribe:input_type -> notifications.v1.UnsubscribeRequest
	2, // 8: notifications.v1.Notifications.RegisterInstallation:output_type -> notifications.v1.RegisterInstallationResponse
	9, // 9: notifications.v1.Notifications.DeleteInstallation:output_type -> google.protobuf.Empty
	9, // 10: notifications.v1.Notifications.Subscribe:output_type -> google.protobuf.Empty
	9, // 11: notifications.v1.Notifications.SubscribeWithMetadata:output_type -> google.protobuf.Empty
	9, // 12: notifications.v1.Notifications.Unsubscribe:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notifications_v1_service_proto_init() }
func file_notifications_v1_service_proto_init() {
	if File_notifications_v1_service_proto != nil {
		return
	}
	file_notifications_v1_service_proto_msgTypes[0].OneofWrappers = []any{
		(*DeliveryMechanism_ApnsDeviceToken)(nil),
		(*DeliveryMechanism_FirebaseDeviceToken)(nil),
		(*DeliveryMechanism_CustomToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_v1_service_proto_rawDesc), len(file_notifications_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_v1_service_proto_goTypes,
		DependencyIndexes: file_notifications_v1_service_proto_depIdxs,
		MessageInfos:      file_notifications_v1_service_proto_msgTypes,
	}.Build()
	File_notifications_v1_service_proto = out.File
	file_notifications_v1_service_proto_goTypes = nil
	file_notifications_v1_service_proto_depIdxs = nil
}
