// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: migration/api/v1/migration.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Xmtp_Migration_Api_V1_D14NMigrationApiClientInterface: Sendable {

    @discardableResult
    func `fetchD14NCutover`(request: SwiftProtobuf.Google_Protobuf_Empty, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Xmtp_Migration_Api_V1_FetchD14nCutoverResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `fetchD14NCutover`(request: SwiftProtobuf.Google_Protobuf_Empty, headers: Connect.Headers) async -> ResponseMessage<Xmtp_Migration_Api_V1_FetchD14nCutoverResponse>
}

/// Concrete implementation of `Xmtp_Migration_Api_V1_D14NMigrationApiClientInterface`.
public final class Xmtp_Migration_Api_V1_D14NMigrationApiClient: Xmtp_Migration_Api_V1_D14NMigrationApiClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `fetchD14NCutover`(request: SwiftProtobuf.Google_Protobuf_Empty, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Xmtp_Migration_Api_V1_FetchD14nCutoverResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/xmtp.migration.api.v1.D14nMigrationApi/FetchD14nCutover", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `fetchD14NCutover`(request: SwiftProtobuf.Google_Protobuf_Empty, headers: Connect.Headers = [:]) async -> ResponseMessage<Xmtp_Migration_Api_V1_FetchD14nCutoverResponse> {
        return await self.client.unary(path: "/xmtp.migration.api.v1.D14nMigrationApi/FetchD14nCutover", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let fetchD14NCutover = Connect.MethodSpec(name: "FetchD14nCutover", service: "xmtp.migration.api.v1.D14nMigrationApi", type: .unary)
        }
    }
}
